version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: AzureShop/WebApi/Dockerfile
    ports:
      - "5000:80"

  frontend:
    build:
      context: .
      dockerfile: produit-frontend/Dockerfile
    ports:
      - "10000:80"
    depends_on:
      - backend
