version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: .
      dockerfile: produit-frontend/Dockerfile
    ports:
      - "4200:80"
