services:
  - type: web
    name: azure-backend
    env: docker
    plan: free
    dockerfilePath: ./AzureShop/WebApi/Dockerfile
    buildCommand: "" # pas nécessaire si ton Dockerfile fait déjà le build
    startCommand: "dotnet WebApi.dll"
    autoDeploy: true
    rootDir: AzureShop/WebApi

  - type: web
    name: azure-frontend
    env: docker
    plan: free
    dockerfilePath: ./produit-frontend/Dockerfile
    buildCommand: "" # idem, déjà dans Dockerfile
    startCommand: "" # nginx démarre automatiquement
    autoDeploy: true
    rootDir: produit-frontend
