services:
  - type: web
    name: azure-backend
    env: docker
    plan: free
    dockerfilePath: AzureShop/WebApi/Dockerfile
    buildFilter:
      paths:
        - AzureShop/WebApi/**
    autoDeploy: true

services:
  - type: web
    name: azure-frontend
    env: docker
    plan: free
    dockerfilePath: ./produit-frontend/Dockerfile
    autoDeploy: true