services:
  - type: web
    name: azure-frontend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - produit-frontend/**
    autoDeploy: true

  - type: web
    name: azure-backend
    env: docker
    plan: free
    dockerfilePath: AzureShop/WebApi/Dockerfile
    autoDeploy: true
