services:
  - type: web
    name: azure-backend
    env: docker
    plan: free
    dockerfilePath: AzureShop/WebApi/Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true

  - type: web
    name: azure-frontend
    env: docker
    plan: free
    dockerfilePath: produit-frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
