# Build step
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build -- --output-path=dist

# Runtime step
FROM nginx:alpine
COPY --from=build /app/dist/produit-frontend /usr/share/nginx/html
COPY ./static/_redirects /usr/share/nginx/html/_redirects
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
